name: Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write
  packages: write

env:
  REGISTRY: "${{ vars.PUBLIC_REGISTRY }}"
  REGISTRY_TOKEN: "${{ secrets.REGISTRY_TOKEN }}"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  github-release:
    runs-on: 'org-cnrancher-runner-dind-x64'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: GitHub Release
        uses: ./.github/actions/github-release
  image-build-amd64:
    runs-on: 'org-cnrancher-runner-dind-x64'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build Image
        uses: ./.github/actions/image-build
  image-build-arm64:
    runs-on: 'org-cnrancher-runner-dind-arm64'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build Image
        uses: ./.github/actions/image-build
  image-manifest:
    needs: [ image-build-amd64, image-build-arm64 ]
    runs-on: 'org-cnrancher-runner-dind-x64'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Image Manifest
        uses: ./.github/actions/image-manifest
